//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Providers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// City.
    /// </summary>
    // *** Start programmer edit section *** (City CustomAttributes)

    // *** End programmer edit section *** (City CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Cities", new string[] {
            "Name"})]
    public class City : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (City CustomMembers)

        // *** End programmer edit section *** (City CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (City.Name CustomAttributes)

        // *** End programmer edit section *** (City.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (City.Name Get start)

                // *** End programmer edit section *** (City.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (City.Name Get end)

                // *** End programmer edit section *** (City.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (City.Name Set start)

                // *** End programmer edit section *** (City.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (City.Name Set end)

                // *** End programmer edit section *** (City.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Cities" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Cities
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Cities", typeof(IIS.Providers.City));
                }
            }
        }
    }
}
