//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Providers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Provider.
    /// </summary>
    // *** Start programmer edit section *** (Provider CustomAttributes)

    // *** End programmer edit section *** (Provider CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Providers", new string[] {
            "Name"})]
    public class Provider : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Provider CustomMembers)

        // *** End programmer edit section *** (Provider CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Provider.Name CustomAttributes)

        // *** End programmer edit section *** (Provider.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Provider.Name Get start)

                // *** End programmer edit section *** (Provider.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Provider.Name Get end)

                // *** End programmer edit section *** (Provider.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Provider.Name Set start)

                // *** End programmer edit section *** (Provider.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Provider.Name Set end)

                // *** End programmer edit section *** (Provider.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Providers" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Providers
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Providers", typeof(IIS.Providers.Provider));
                }
            }
        }
    }
}
