//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Providers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Subscriber.
    /// </summary>
    // *** Start programmer edit section *** (Subscriber CustomAttributes)

    // *** End programmer edit section *** (Subscriber CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SubcriberAll", new string[] {
            "Surname",
            "Name",
            "Lastname",
            "PhoneNumber",
            "Passport",
            "Provider.Name",
            "City.Name"})]
    public class Subscriber : ICSSoft.STORMNET.DataObject
    {
        
        private string fSurname;
        
        private string fName;
        
        private string fLastname;
        
        private string fPhoneNumber;
        
        private string fPassport;
        
        private IIS.Providers.Provider fProvider;
        
        private IIS.Providers.City fCity;
        
        // *** Start programmer edit section *** (Subscriber CustomMembers)

        // *** End programmer edit section *** (Subscriber CustomMembers)

        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Subscriber.Surname CustomAttributes)

        // *** End programmer edit section *** (Subscriber.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Subscriber.Surname Get start)

                // *** End programmer edit section *** (Subscriber.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Subscriber.Surname Get end)

                // *** End programmer edit section *** (Subscriber.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscriber.Surname Set start)

                // *** End programmer edit section *** (Subscriber.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Subscriber.Surname Set end)

                // *** End programmer edit section *** (Subscriber.Surname Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Subscriber.Name CustomAttributes)

        // *** End programmer edit section *** (Subscriber.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Subscriber.Name Get start)

                // *** End programmer edit section *** (Subscriber.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Subscriber.Name Get end)

                // *** End programmer edit section *** (Subscriber.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscriber.Name Set start)

                // *** End programmer edit section *** (Subscriber.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Subscriber.Name Set end)

                // *** End programmer edit section *** (Subscriber.Name Set end)
            }
        }
        
        /// <summary>
        /// Lastname.
        /// </summary>
        // *** Start programmer edit section *** (Subscriber.Lastname CustomAttributes)

        // *** End programmer edit section *** (Subscriber.Lastname CustomAttributes)
        [StrLen(255)]
        public virtual string Lastname
        {
            get
            {
                // *** Start programmer edit section *** (Subscriber.Lastname Get start)

                // *** End programmer edit section *** (Subscriber.Lastname Get start)
                string result = this.fLastname;
                // *** Start programmer edit section *** (Subscriber.Lastname Get end)

                // *** End programmer edit section *** (Subscriber.Lastname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscriber.Lastname Set start)

                // *** End programmer edit section *** (Subscriber.Lastname Set start)
                this.fLastname = value;
                // *** Start programmer edit section *** (Subscriber.Lastname Set end)

                // *** End programmer edit section *** (Subscriber.Lastname Set end)
            }
        }
        
        /// <summary>
        /// PhoneNumber.
        /// </summary>
        // *** Start programmer edit section *** (Subscriber.PhoneNumber CustomAttributes)

        // *** End programmer edit section *** (Subscriber.PhoneNumber CustomAttributes)
        [StrLen(255)]
        public virtual string PhoneNumber
        {
            get
            {
                // *** Start programmer edit section *** (Subscriber.PhoneNumber Get start)

                // *** End programmer edit section *** (Subscriber.PhoneNumber Get start)
                string result = this.fPhoneNumber;
                // *** Start programmer edit section *** (Subscriber.PhoneNumber Get end)

                // *** End programmer edit section *** (Subscriber.PhoneNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscriber.PhoneNumber Set start)

                // *** End programmer edit section *** (Subscriber.PhoneNumber Set start)
                this.fPhoneNumber = value;
                // *** Start programmer edit section *** (Subscriber.PhoneNumber Set end)

                // *** End programmer edit section *** (Subscriber.PhoneNumber Set end)
            }
        }
        
        /// <summary>
        /// Passport.
        /// </summary>
        // *** Start programmer edit section *** (Subscriber.Passport CustomAttributes)

        // *** End programmer edit section *** (Subscriber.Passport CustomAttributes)
        [StrLen(255)]
        public virtual string Passport
        {
            get
            {
                // *** Start programmer edit section *** (Subscriber.Passport Get start)

                // *** End programmer edit section *** (Subscriber.Passport Get start)
                string result = this.fPassport;
                // *** Start programmer edit section *** (Subscriber.Passport Get end)

                // *** End programmer edit section *** (Subscriber.Passport Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscriber.Passport Set start)

                // *** End programmer edit section *** (Subscriber.Passport Set start)
                this.fPassport = value;
                // *** Start programmer edit section *** (Subscriber.Passport Set end)

                // *** End programmer edit section *** (Subscriber.Passport Set end)
            }
        }
        
        /// <summary>
        /// Subscriber.
        /// </summary>
        // *** Start programmer edit section *** (Subscriber.Provider CustomAttributes)

        // *** End programmer edit section *** (Subscriber.Provider CustomAttributes)
        [PropertyStorage(new string[] {
                "Provider"})]
        [NotNull()]
        public virtual IIS.Providers.Provider Provider
        {
            get
            {
                // *** Start programmer edit section *** (Subscriber.Provider Get start)

                // *** End programmer edit section *** (Subscriber.Provider Get start)
                IIS.Providers.Provider result = this.fProvider;
                // *** Start programmer edit section *** (Subscriber.Provider Get end)

                // *** End programmer edit section *** (Subscriber.Provider Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscriber.Provider Set start)

                // *** End programmer edit section *** (Subscriber.Provider Set start)
                this.fProvider = value;
                // *** Start programmer edit section *** (Subscriber.Provider Set end)

                // *** End programmer edit section *** (Subscriber.Provider Set end)
            }
        }
        
        /// <summary>
        /// Subscriber.
        /// </summary>
        // *** Start programmer edit section *** (Subscriber.City CustomAttributes)

        // *** End programmer edit section *** (Subscriber.City CustomAttributes)
        [PropertyStorage(new string[] {
                "City"})]
        [NotNull()]
        public virtual IIS.Providers.City City
        {
            get
            {
                // *** Start programmer edit section *** (Subscriber.City Get start)

                // *** End programmer edit section *** (Subscriber.City Get start)
                IIS.Providers.City result = this.fCity;
                // *** Start programmer edit section *** (Subscriber.City Get end)

                // *** End programmer edit section *** (Subscriber.City Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscriber.City Set start)

                // *** End programmer edit section *** (Subscriber.City Set start)
                this.fCity = value;
                // *** Start programmer edit section *** (Subscriber.City Set end)

                // *** End programmer edit section *** (Subscriber.City Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SubcriberAll" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubcriberAll
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubcriberAll", typeof(IIS.Providers.Subscriber));
                }
            }
        }
    }
}
